# Generated by Django 5.0.2 on 2024-02-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('farmer_name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'farmers',
            },
        ),
    ]
