# Generated by Django 5.0.2 on 2024-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='time',
            field=models.TimeField(),
        ),
    ]
