# Generated by Django 5.0.2 on 2024-02-22 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0002_alter_farmers_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='total',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
