# Generated by Django 5.0.2 on 2024-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0003_farmers_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_owner', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'resister_owners',
            },
        ),
        migrations.CreateModel(
            name='register_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_rate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'register_rate',
            },
        ),
    ]
