# Generated by Django 5.0.2 on 2024-02-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0004_register_owners_register_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_rate',
            name='new_rate',
            field=models.TextField(max_length=50),
        ),
    ]
