# Generated by Django 5.0.2 on 2024-02-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0005_alter_register_rate_new_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_owners',
        ),
        migrations.DeleteModel(
            name='register_rate',
        ),
    ]
