# Generated by Django 5.0.2 on 2024-02-23 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0006_delete_register_owners_delete_register_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
