# Generated by Django 5.0.2 on 2024-02-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvesterapp', '0007_farmers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmers',
            name='status',
        ),
    ]
